/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    IAntDesignAlertFilled: typeof import('~icons/ant-design/alert-filled')['default']
    IAntDesignAudioFilled: typeof import('~icons/ant-design/audio-filled')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IEpChatDotSquare: typeof import('~icons/ep/chat-dot-square')['default']
    Line: typeof import('./../views/line.vue')['default']
    RotateBox: typeof import('./../views/rotate-box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
